import {
  Activity,
  Bell,
  Building2,
  Calendar,
  CircleDot,
  CreditCard,
  Globe2,
  LayoutDashboard,
  LayoutGrid,
  Package,
  Percent,
  Pill,
  Receipt,
  ScrollText,
  Settings,
  Shapes,
  ShieldAlert,
  ShoppingCart,
  Stethoscope,
  Store,
  Tag,
  Timer,
  Trophy,
  Truck,
  Users,
  UtensilsCrossed,
  Wallet,
  Warehouse,
  type LucideIcon,
} from "lucide-react";
import type { ModuleId } from "@/templates/types";

export const MODULE_ICONS: Partial<Record<ModuleId | string, LucideIcon>> = {
  dashboard: LayoutDashboard,
  pos: ShoppingCart,
  orders: ShoppingCart,
  sales: Receipt,
  products: LayoutGrid,
  categories: Shapes,
  inventory: Package,
  departments: Warehouse,
  batches: Package,
  expiry: Calendar,
  purchases: CreditCard,
  suppliers: Truck,
  promotions: Tag,
  "price-management": Tag,
  customers: Users,
  counters: Store,
  branches: Building2,
  reports: Activity,
  settings: Settings,
  staff: Users,
  tables: CircleDot,
  kitchen: UtensilsCrossed,
  menu: UtensilsCrossed,
  "public-catalog": Globe2,
  invoices: Receipt,
  users: Users,
  prescriptions: Stethoscope,
  cdss: Pill,
  "controlled-substances": ShieldAlert,
  accounting: CreditCard,
  shifts: Calendar,
  returns: Receipt,
  "billing-pricing": Timer,
  "credit-udhar": Wallet,
  discounts: Percent,
  expenses: CreditCard,
  "audit-logs": ScrollText,
  notifications: Bell,
  tournaments: Trophy,
  loyalty: Tag,
  "table-booking": Calendar,
  subscriptions: CreditCard,
  memberships: Users,
};

export function resolveModuleIcon(moduleId: string): LucideIcon {
  return MODULE_ICONS[moduleId] ?? LayoutGrid;
}
