import type { IndustryTemplate } from "./types";
import {
  SNOOKER_OPTIONAL_MODULES,
  SNOOKER_POS_INDUSTRY_ID,
  SNOOKER_PRODUCT_SCOPE,
  SNOOKER_SIDEBAR_MODULES,
} from "./snooker-pos";

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    id: "retail-store",
    name: "Retail Store",
    description: "General retail with barcode POS, inventory, and daily cash summary.",
    family: "general-retail",
    theme: { accent: "blue", icon: "store" },
    labels: { product: "Product", products: "Products" },
    modules: ["dashboard", "pos", "sales", "products", "categories", "orders", "inventory", "purchases", "suppliers", "customers", "returns", "expenses", "staff", "reports", "settings"],
    optionalModules: ["accounting", "hr", "multi-branch", "delivery"],
    dashboardCards: ["today-sales", "total-transactions", "gross-profit", "low-stock", "top-products", "pending-purchases"],
    roles: ["Owner", "Cashier", "Store Manager", "Inventory Clerk"],
    workflows: ["Quick POS sale", "Stock adjustment", "Purchase receive", "Daily cash close"],
    specialScreens: ["Barcode product search", "Quick POS grid", "Stock adjustment drawer", "Daily cash summary"],
    features: {},
  },
  {
    id: "pharmacy",
    name: "Pharmacy",
    description: "Dual-market pharmacy ERP for Pakistan (DRAP/FBR/GST) and the UK (MHRA/HMRC/NHS).",
    family: "high-volume-retail",
    theme: { accent: "green", icon: "pill" },
    labels: { product: "Medicine", products: "Medicines", customer: "Patient", customers: "Patients", order: "Sale", orders: "Sales" },
    modules: ["dashboard", "pos", "products", "categories", "batches", "expiry", "inventory", "prescriptions", "cdss", "controlled-substances", "purchases", "suppliers", "customers", "sales", "returns", "reports", "accounting", "shifts", "staff", "settings"],
    optionalModules: ["accounting", "multi-branch", "hr"],
    dashboardCards: ["today-sales", "expiring-items", "expired-items", "low-stock", "batch-value", "pending-prescriptions"],
    roles: ["Owner", "Pharmacy Manager", "Pharmacist", "Shift Incharge", "Cashier", "Inventory Manager"],
    workflows: ["Prescription fill", "Batch receive", "Expiry check", "Fast barcode sale"],
    specialScreens: ["Batch & expiry table", "Prescription upload preview", "Generic name search", "Batch-wise stock drawer"],
    features: { batchTracking: true, expiryTracking: true },
  },
  {
    id: "restaurant",
    name: "Restaurant",
    description: "Full-service dining with tables, kitchen display, modifiers, and recipes.",
    family: "food-operations",
    theme: { accent: "orange", icon: "utensils" },
    labels: { product: "Menu Item", products: "Menu", order: "Order", orders: "Orders" },
    modules: [
      "dashboard",
      "menu",
      "categories",
      "public-catalog",
      "tables",
      "sales",
      "orders",
      "kitchen",
      "staff",
      "modifiers",
      "inventory",
      "recipes",
      "purchases",
      "suppliers",
      "customers",
      "shifts",
      "reports",
      "settings",
    ],
    optionalModules: ["pos", "delivery", "accounting", "hr", "multi-branch"],
    dashboardCards: ["today-sales", "active-orders", "tables-occupied", "kitchen-delays", "avg-order-value", "low-stock-ingredients"],
    roles: ["Owner", "Cashier", "Waiter", "Kitchen Staff", "Manager"],
    workflows: ["Dine-in order", "Kitchen prep", "Split bill", "Shift close"],
    specialScreens: ["Floor & table map", "Kitchen Display System", "Modifier selection", "Recipe builder", "Split bill modal"],
    features: { kitchen: true, tables: true },
  },
  {
    id: "boutique",
    name: "Boutique",
    description: "Fashion retail with size/colour matrix, collections, and alterations.",
    family: "fashion-retail",
    theme: { accent: "rose", icon: "shirt" },
    labels: { product: "Style", products: "Styles" },
    modules: ["dashboard", "pos", "products", "collections", "variants", "inventory", "sales-orders", "customers", "measurements", "alterations", "returns", "purchases", "suppliers", "reports", "settings"],
    optionalModules: ["delivery", "accounting", "multi-branch"],
    dashboardCards: ["today-sales", "best-collection", "low-stock-sizes", "pending-alterations", "customer-orders", "returns-exchanges"],
    roles: ["Owner", "Stylist", "Cashier", "Alteration Tailor"],
    workflows: ["Variant sale", "Measurement capture", "Alteration job", "Exchange"],
    specialScreens: ["Size/colour matrix", "Collection builder", "Measurement profile", "Exchange reason modal"],
    features: { variants: true },
  },
  {
    id: "salon-spa",
    name: "Salon / SPA",
    description: "Appointment-first service business with schedules, packages, and commissions.",
    family: "service-business",
    theme: { accent: "violet", icon: "sparkles" },
    labels: { product: "Product", products: "Products", customer: "Guest", customers: "Guests" },
    modules: ["dashboard", "appointments", "services", "customers", "staff", "schedules", "packages", "memberships", "pos", "products", "inventory", "commissions", "reports", "settings"],
    optionalModules: ["accounting", "hr", "multi-branch"],
    dashboardCards: ["today-appointments", "available-staff", "expected-revenue", "walk-ins", "pending-appointments", "top-service"],
    roles: ["Owner", "Receptionist", "Stylist / Therapist", "Manager"],
    workflows: ["Book appointment", "Walk-in billing", "Package usage", "Commission close"],
    specialScreens: ["Day/week calendar", "Staff availability", "Treatment room picker", "Membership balance"],
    features: { appointments: true },
  },
  {
    id: "bakery",
    name: "Bakery POS",
    description: "Bakery operations with production batches, recipes, and custom cake orders.",
    family: "food-operations",
    theme: { accent: "amber", icon: "cake" },
    labels: { product: "Product", products: "Products", order: "Order", orders: "Orders" },
    modules: ["dashboard", "pos", "orders", "products", "recipes", "production", "custom-orders", "inventory", "batches", "wastage", "purchases", "suppliers", "customers", "reports", "settings"],
    optionalModules: ["delivery", "kitchen", "accounting"],
    dashboardCards: ["today-sales", "production-planned", "custom-orders-due", "wastage", "expiring-items", "ingredient-shortage"],
    roles: ["Owner", "Cashier", "Baker", "Production Lead"],
    workflows: ["Counter sale", "Production plan", "Custom cake order", "Wastage log"],
    specialScreens: ["Production batch board", "Recipe builder", "Custom-order form", "Expiry & wastage table"],
    features: { production: true, batchTracking: true, expiryTracking: true },
  },
  {
    id: "electric-store",
    name: "Electric Store",
    description: "Electronics retail with brands, models, serial numbers, and warranties.",
    family: "general-retail",
    theme: { accent: "slate", icon: "cpu" },
    labels: { product: "Product", products: "Products" },
    modules: ["dashboard", "pos", "products", "brands", "models", "serial-numbers", "inventory", "sales", "warranties", "returns", "purchases", "suppliers", "customers", "reports", "settings"],
    optionalModules: ["delivery", "accounting", "multi-branch"],
    dashboardCards: ["today-sales", "warranty-claims", "low-stock", "product-returns", "top-brands", "pending-purchases"],
    roles: ["Owner", "Cashier", "Technician", "Store Manager"],
    workflows: ["Serial sale", "Warranty claim", "Model lookup", "Return intake"],
    specialScreens: ["Serial-number entry", "Warranty claim screen", "Spec tabs", "Model comparison"],
    features: { serialNumbers: true },
  },
  {
    id: "jewellery",
    name: "Jewellery Shop",
    description: "Jewellery retail with weight, purity, making charges, and custom orders.",
    family: "general-retail",
    theme: { accent: "amber", icon: "gem" },
    labels: { product: "Piece", products: "Pieces" },
    modules: ["dashboard", "pos", "products", "collections", "metals", "stones", "inventory", "custom-orders", "repairs", "customers", "sales", "purchases", "certificates", "reports", "settings"],
    optionalModules: ["accounting", "multi-branch", "delivery"],
    dashboardCards: ["today-sales", "inventory-value", "custom-orders", "repairs-pending", "metal-stock", "outstanding-balances"],
    roles: ["Owner", "Sales Advisor", "Goldsmith", "Cashier"],
    workflows: ["Weight-based pricing", "Custom design order", "Repair intake", "Certificate attach"],
    specialScreens: ["Weight & purity calculator", "Metal rate panel", "Certificate upload", "Repair tracker"],
    features: {},
  },
  {
    id: "toys-store",
    name: "Toys Store",
    description: "Toy retail with age groups, brands, bundles, and seasonal promotions.",
    family: "general-retail",
    theme: { accent: "orange", icon: "toy" },
    labels: { product: "Toy", products: "Toys" },
    modules: ["dashboard", "pos", "products", "categories", "brands", "age-groups", "inventory", "sales", "bundles", "promotions", "purchases", "suppliers", "customers", "reports", "settings"],
    optionalModules: ["delivery", "accounting", "multi-branch"],
    dashboardCards: ["today-sales", "top-age-group", "low-stock", "seasonal-products", "top-brands", "active-promotions"],
    roles: ["Owner", "Cashier", "Floor Staff"],
    workflows: ["Age-filtered sale", "Bundle sale", "Gift wrap add-on", "Promo apply"],
    specialScreens: ["Age-group filters", "Bundle builder", "Gift wrapping option", "Safety info panel"],
    features: {},
  },
  {
    id: "food-cafe",
    name: "Food / Cafe",
    description: "Lighter restaurant template focused on counter POS, modifiers, and takeaway.",
    family: "food-operations",
    theme: { accent: "teal", icon: "coffee" },
    labels: { product: "Menu Item", products: "Menu", order: "Order", orders: "Orders" },
    modules: ["dashboard", "pos", "orders", "menu", "modifiers", "kitchen", "takeaway", "inventory", "recipes", "purchases", "customers", "staff", "reports", "settings"],
    optionalModules: ["tables", "delivery", "accounting"],
    dashboardCards: ["today-sales", "orders-in-progress", "avg-prep-time", "best-selling-item", "takeaway-orders", "ingredient-shortage"],
    roles: ["Owner", "Cashier", "Barista", "Kitchen Staff"],
    workflows: ["Quick counter order", "Token pickup", "Kitchen queue", "Takeaway close"],
    specialScreens: ["Counter-first POS", "Coffee/size modifiers", "Order token view", "Quick kitchen queue"],
    features: { kitchen: true },
  },
  {
    id: "furniture",
    name: "Furniture Store",
    description: "Furniture retail with quotations, custom orders, delivery, and installation.",
    family: "general-retail",
    theme: { accent: "slate", icon: "sofa" },
    labels: { product: "Product", products: "Products" },
    modules: ["dashboard", "pos", "products", "collections", "custom-orders", "quotations", "inventory", "customers", "delivery", "installations", "purchases", "suppliers", "sales", "reports", "settings"],
    optionalModules: ["accounting", "multi-branch", "hr"],
    dashboardCards: ["today-sales", "pending-quotations", "custom-orders", "scheduled-deliveries", "installations-pending", "low-stock"],
    roles: ["Owner", "Sales Consultant", "Warehouse", "Installer"],
    workflows: ["Quotation", "Custom order stages", "Delivery schedule", "Installation close"],
    specialScreens: ["Dimensions & finishes", "Quotation builder", "Delivery scheduler", "Installation status"],
    features: { delivery: true },
  },
  {
    id: "supermarket",
    name: "Supermarkets",
    description: "High-volume retail with fast barcode POS, departments, batches, and counters.",
    family: "high-volume-retail",
    theme: { accent: "green", icon: "shopping-cart" },
    labels: { product: "Product", products: "Products" },
    modules: ["dashboard", "pos", "sales", "products", "departments", "inventory", "batches", "expiry", "purchases", "suppliers", "promotions", "price-management", "customers", "counters", "branches", "reports", "settings"],
    optionalModules: ["accounting", "hr", "multi-branch"],
    dashboardCards: ["today-sales", "active-counters", "fast-selling", "low-stock", "expiring-items", "purchase-value"],
    roles: ["Owner", "Cashier", "Department Lead", "Store Manager"],
    workflows: ["Fast barcode sale", "Weighted item sale", "Bulk price update", "Counter close"],
    specialScreens: ["Keyboard-friendly fast POS", "Weighted item input", "Bulk price update", "Counter/terminal view"],
    features: { batchTracking: true, expiryTracking: true },
  },
  {
    id: "manufacturing",
    name: "Manufacturing",
    description: "Production-focused template with BOM, work centres, QC, and finished stock.",
    family: "production",
    theme: { accent: "slate", icon: "factory" },
    labels: { product: "Finished Good", products: "Finished Goods" },
    modules: ["dashboard", "raw-materials", "products", "bom", "production-orders", "production", "work-centres", "quality-control", "finished-stock", "purchases", "suppliers", "sales-orders", "customers", "reports", "settings"],
    optionalModules: ["accounting", "hr", "multi-branch"],
    dashboardCards: ["production-in-progress", "raw-material-shortages", "planned-production", "completed-production", "rejected-quantity", "finished-stock-value"],
    roles: ["Owner", "Production Manager", "QC Inspector", "Store Keeper"],
    workflows: ["Create BOM", "Issue production order", "Stage progress", "QC checklist", "Finished stock receipt"],
    specialScreens: ["BOM builder", "Kanban production board", "QC checklist", "Production cost summary"],
    features: { production: true },
  },
  {
    id: "auto-parts",
    name: "Auto Parts",
    description: "Parts retail with vehicle compatibility, OEM numbers, and warranties.",
    family: "general-retail",
    theme: { accent: "blue", icon: "car" },
    labels: { product: "Part", products: "Parts", order: "Order", orders: "Orders" },
    modules: ["dashboard", "pos", "products", "categories", "orders", "brands", "vehicle-compatibility", "inventory", "serial-numbers", "sales", "returns", "warranties", "purchases", "suppliers", "customers", "reports", "settings"],
    optionalModules: ["delivery", "accounting", "multi-branch"],
    dashboardCards: ["today-sales", "low-stock", "fast-moving-parts", "warranty-claims", "top-vehicle-brands", "pending-purchases"],
    roles: ["Owner", "Counter Sales", "Warehouse", "Technician"],
    workflows: ["Compatibility search", "Part sale", "Warranty return", "OEM lookup"],
    specialScreens: ["Vehicle compatibility selector", "OEM / part number search", "Serial & warranty view"],
    features: { serialNumbers: true },
  },
  {
    id: "book-store",
    name: "Book Store",
    description: "Bookstore catalog with ISBN, authors, publishers, and reservations.",
    family: "general-retail",
    theme: { accent: "violet", icon: "book" },
    labels: { product: "Book", products: "Books" },
    modules: ["dashboard", "pos", "products", "categories", "authors", "publishers", "inventory", "sales", "customers", "orders", "returns", "purchases", "suppliers", "reports", "settings"],
    optionalModules: ["delivery", "accounting", "multi-branch"],
    dashboardCards: ["today-sales", "best-selling-books", "low-stock", "top-authors", "customer-orders", "recently-added"],
    roles: ["Owner", "Cashier", "Catalog Manager"],
    workflows: ["ISBN scan sale", "Author browse", "Reserve book", "Publisher receive"],
    specialScreens: ["ISBN metadata form", "Book cover preview", "Author / publisher filters", "Reserved status"],
    features: {},
  },
  {
    id: SNOOKER_POS_INDUSTRY_ID,
    name: "Snooker POS",
    description:
      "Club POS for snooker and pool: live tables, Single/Double/Century billing, sessions, Udhar credit, daily cash close, and multi-branch reporting.",
    family: "service-business",
    theme: { accent: "green", icon: "snooker" },
    labels: {
      product: "Game",
      products: "Games",
      customer: "Player",
      customers: "Players",
      order: "Session",
      orders: "Sessions",
    },
    modules: [...SNOOKER_SIDEBAR_MODULES],
    optionalModules: [...SNOOKER_OPTIONAL_MODULES],
    dashboardCards: [
      "tables-occupied",
      "active-sessions",
      "today-sales",
      "gross-profit",
      "cash-on-hand",
      "overdue-credit",
    ],
    roles: ["Owner", "Manager", "Cashier", "Accountant", "Viewer", "Super Admin"],
    workflows: [
      "Table Selection → Game Type → Start Session → Timer/Game → Finish → Discount → Cash/Udhar → Receipt → Table Available",
      "Single Game flat-rate billing",
      "Double Game flat-rate billing",
      "Century timer Start / Pause / Resume / Stop",
      "Daily opening cash",
      "Daily closing reconciliation with variance approval",
      "Udhar sale, partial recovery, and statement",
    ],
    specialScreens: [
      "Live table floor (available, occupied, reserved, maintenance)",
      "POS session: Single, Double, and Century",
      "Century timer with per-minute pricing, minimum duration, and rounding",
      "Discount reason and approval",
      "Cash / Udhar payment and receipt",
      "Daily opening and closing cash drawer",
      "Credit ledger and overdue alerts",
    ],
    features: { tables: true, timeBilling: true, creditLedger: true },
    productScope: SNOOKER_PRODUCT_SCOPE,
  },
];

export function getIndustryById(id: string): IndustryTemplate | undefined {
  return INDUSTRY_TEMPLATES.find((t) => t.id === id);
}

export const FAMILY_LABELS: Record<IndustryTemplate["family"], string> = {
  "general-retail": "General Retail",
  "high-volume-retail": "High-Volume Retail",
  "food-operations": "Food Operations",
  "fashion-retail": "Fashion Retail",
  "service-business": "Service Business",
  production: "Production",
};
