export type IndustryFamily =
  | "general-retail"
  | "high-volume-retail"
  | "food-operations"
  | "fashion-retail"
  | "service-business"
  | "production";

export type ThemeMode = "light" | "dark";

export type AccentColor =
  | "blue"
  | "green"
  | "teal"
  | "amber"
  | "rose"
  | "violet"
  | "slate"
  | "orange";

export type ModuleId =
  | "dashboard"
  | "pos"
  | "orders"
  | "sales"
  | "products"
  | "categories"
  | "inventory"
  | "purchases"
  | "suppliers"
  | "customers"
  | "returns"
  | "expenses"
  | "staff"
  | "reports"
  | "settings"
  | "tables"
  | "kitchen"
  | "menu"
  | "modifiers"
  | "recipes"
  | "shifts"
  | "batches"
  | "expiry"
  | "prescriptions"
  | "collections"
  | "variants"
  | "measurements"
  | "alterations"
  | "appointments"
  | "services"
  | "schedules"
  | "packages"
  | "memberships"
  | "commissions"
  | "production"
  | "custom-orders"
  | "wastage"
  | "brands"
  | "models"
  | "serial-numbers"
  | "warranties"
  | "metals"
  | "stones"
  | "repairs"
  | "certificates"
  | "age-groups"
  | "bundles"
  | "promotions"
  | "takeaway"
  | "delivery"
  | "quotations"
  | "installations"
  | "departments"
  | "price-management"
  | "counters"
  | "branches"
  | "raw-materials"
  | "bom"
  | "production-orders"
  | "work-centres"
  | "quality-control"
  | "finished-stock"
  | "sales-orders"
  | "vehicle-compatibility"
  | "authors"
  | "publishers"
  | "accounting"
  | "hr"
  | "multi-branch";

export type DashboardCardId =
  | "today-sales"
  | "total-transactions"
  | "gross-profit"
  | "low-stock"
  | "top-products"
  | "pending-purchases"
  | "expiring-items"
  | "expired-items"
  | "batch-value"
  | "pending-prescriptions"
  | "active-orders"
  | "tables-occupied"
  | "kitchen-delays"
  | "avg-order-value"
  | "low-stock-ingredients"
  | "best-collection"
  | "low-stock-sizes"
  | "pending-alterations"
  | "customer-orders"
  | "returns-exchanges"
  | "today-appointments"
  | "available-staff"
  | "expected-revenue"
  | "walk-ins"
  | "pending-appointments"
  | "top-service"
  | "production-planned"
  | "custom-orders-due"
  | "wastage"
  | "ingredient-shortage"
  | "warranty-claims"
  | "product-returns"
  | "top-brands"
  | "inventory-value"
  | "custom-orders"
  | "repairs-pending"
  | "metal-stock"
  | "outstanding-balances"
  | "top-age-group"
  | "seasonal-products"
  | "active-promotions"
  | "orders-in-progress"
  | "avg-prep-time"
  | "best-selling-item"
  | "takeaway-orders"
  | "pending-quotations"
  | "scheduled-deliveries"
  | "installations-pending"
  | "active-counters"
  | "fast-selling"
  | "purchase-value"
  | "production-in-progress"
  | "raw-material-shortages"
  | "planned-production"
  | "completed-production"
  | "rejected-quantity"
  | "finished-stock-value"
  | "fast-moving-parts"
  | "top-vehicle-brands"
  | "best-selling-books"
  | "top-authors"
  | "recently-added";

export type IndustryTemplate = {
  id: string;
  name: string;
  description: string;
  family: IndustryFamily;
  theme: {
    accent: AccentColor;
    icon: string;
  };
  labels: {
    product: string;
    products: string;
    customer?: string;
    customers?: string;
    order?: string;
    orders?: string;
  };
  modules: ModuleId[];
  optionalModules: ModuleId[];
  dashboardCards: DashboardCardId[];
  roles: string[];
  workflows: string[];
  specialScreens: string[];
  features: {
    batchTracking?: boolean;
    expiryTracking?: boolean;
    kitchen?: boolean;
    tables?: boolean;
    appointments?: boolean;
    production?: boolean;
    variants?: boolean;
    serialNumbers?: boolean;
    delivery?: boolean;
  };
};

export type CustomizedTemplateConfig = {
  id: string;
  createdAt: string;
  businessName: string;
  industryId: string;
  industryName: string;
  family: IndustryFamily;
  currency: string;
  location: string;
  branchCount: number;
  logoDataUrl?: string;
  accent: AccentColor;
  themeMode: ThemeMode;
  enabledModules: ModuleId[];
  navigation: Array<{ moduleId: ModuleId; label: string; visible: boolean }>;
  dashboardCards: DashboardCardId[];
  labels: IndustryTemplate["labels"];
};
